# Generated by Django 4.0.6 on 2023-01-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user', models.CharField(max_length=120, null=True)),
                ('app_name', models.CharField(max_length=120, unique=True)),
                ('app_link', models.CharField(max_length=200)),
                ('app_image', models.ImageField(upload_to='applicationImage')),
                ('app_category', models.CharField(max_length=120)),
                ('app_subcategory', models.CharField(max_length=120)),
                ('app_points', models.CharField(max_length=120)),
            ],
        ),
    ]
