# Generated by Django 4.0.6 on 2023-01-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='user_points',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_image', models.ImageField(blank=True, null=True, upload_to='taskImage')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_name', to='accounts.applicationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
